### ISSUE TITLE
replace the ipld implementation with rust-ipld

### ISSUE THREAD

**Issue by dvc94ch** [ipfs-rust/rust-ipfs#54]
depends on https://github.com/ipfs-rust/rust-ipld/pull/22

**Comment by aphelionz** [comment]
@dvc94ch Do you envision this as a subcrate inside of `rust-ipfs` kind of like the `http` crate is now? If so I think this is a good idea and a critical improvement over the current code organization :+1:

**Comment by vmx** [comment]
I'd like to have the ipld related things in it's own repo (rust-ipld) as it is an independent project (just like libp2p is).

**Comment by aphelionz** [comment]
You would agree that `rust-ipfs` should still implement `rust-ipld` though, yes?

**Comment by vmx** [comment]
`rust-ipfs` will use `rust-ipld` and help with it's development (hopfully).

**Comment by vmx** [comment]
The scope of `rust-ipld` is bigger than what ipfs might need.

**Comment by aphelionz** [comment]
I see, and also looking at the discussion in https://github.com/ipfs-rust/rust-ipld/issues/14 it seems that IPLD is meant to be somewhat independent of the substrate it's working on - so the links might come from somewhere besides IPFS... is my understanding correct?

**Comment by vmx** [comment]
Yes. IPLD is it's own independent project (like IPFS or libp2p). IPFS is using parts of IPLD and libp2p.

**Comment by aphelionz** [comment]
Ok, I'm persuaded to not want it in a subcrate anymore :+1:

**Comment by dvc94ch** [comment]
Completely agree with all the above

**Comment by koivunej** [comment]
> The scope of rust-ipld is bigger than what ipfs might need.

For this reason I was thinking that is there a pressing need for this switch, as in, in the scope of the grant, do we need this *now* as opposed to "when entering phase 1.2" or later? During the initial grant planning, we also had an idea of "giving time for @vmx" and others to work on `rust-ipld` as we've now begun with the discussions around block api.

**Comment by dvc94ch** [comment]
the first step would be backporting some of the current implementation that rust-ipld doesn't have yet. it'll help the rust-ipld design by getting practical experience with it's integration. both me and @vmx missed that the prefix was a concept used in bitswap, which we wouldn't have noticed if I hadn't tried updating rust-ipfs to use the PR.

**Comment by koivunej** [comment]
> both me and vmx missed that the prefix was a concept used in bitswap

Ok found [the mention in spec, under wireformat](https://github.com/ipfs/specs/blob/master/BITSWAP.md#wire-format) and the [corresponding lines of code](https://github.com/ipfs-rust/rust-ipfs/blob/master/src/bitswap/ledger.rs#L168-L210). To be honest I am a bit surprised it's there as well but I am a bit confused as to why bitswap talks about CID's instead of plain multihashes in general. Could elaborate why this is sent along the block in bitswap, as it's not mentioned in the spec text other than in the protobuf section. Is it only to allow later checking of "I just received a block on my wantlist according to this cid-prefix which contains the hash to use"?

How is ipld concerned with the cid prefix?

**Comment by vmx** [comment]
> How is ipld concerned with the cid prefix?

Not directly IPLD, but CID. I wanted to remove some API that didn't make much sense to @dvc94ch and me (https://github.com/multiformats/rust-cid/pull/40#issuecomment-595741823). But it makes sense to keep it due to having bitswap.

If rust-ipfs is using rust-ipld (and hence the most recent versions of multiformats like rust-cid), we can detect such things.

**Comment by koivunej** [comment]
Wonder if this the source for this was deleted?

> If rust-ipfs is using rust-ipld (and hence the most recent versions of multiformats like rust-cid), we can detect such things.

Just checked the cid dependency can be updated to 0.4 without breaking anything but the latest master was already used but locked into 2276fa7a8c4aa81d809004643505a7e66f7cf381 (near/before v0.3.2), so I can't see how this `rust-ipld` dependency would've helped here. I wonder if comments in the `rust-cid` would had helped in this particular case, describing the *why* parts of `rust-cid` exist.

Looking at [Davids dag-pb and thiserror PR into rust-ipld](https://github.com/ipfs-rust/rust-ipld/pull/25) it's looking good and I can sort of see a path forward with replacing the ipld side. Perhaps the upgrade should become as a `libipld-dag-cbor`, `libipld-dag-pb`, `libipld-base` dependencies, or does someone else already have a plan? Migration away from the failure to thiserror would probably be great but that should be another issue in it self.

**Comment by dvc94ch** [comment]
should have this done soon, just need to fix the tests in rust-ipfs
