### ISSUE TITLE
Support for /pubsub/ API endpoints

### ISSUE THREAD

**Issue by aphelionz** [ipfs-rust/rust-ipfs#76]
These are likely passthroughs to libp2p functionality. More detail TBD

**Comment by koivunej** [comment]
Looked at this today. From our http api this will require first streaming responses with the subscription.

All http requests to `/pubsub/sub?arg=topic` share the "subscription" and should see the events following the subscription start and not before it (didn't see any tests related to this in the http api tests). Since there is [`tokio::sync::broadcast`](https://docs.rs/tokio/0.2.13/tokio/sync/broadcast/index.html) I was thinking that perhaps the `ipfs::Ipfs` should expose an API which can subscribe to a topic at most once (with single Sink or Sender) and handle the requests coming and going at `ipfs-http` layer. However, as the `/pubsub/peers` is required as well to show known peer_ids through floodsub (I assume) and per topic subset, and it even persists after all subscriptions are dropped, perhaps this tracking needs to be inside the behaviour.

From testing point of view this will depend on #77.

**Comment by koivunej** [comment]
#118 and #120 merged so this can be closed. Briefly the unsupported parts:

 - `go-ipfs` cannot be used as CLI because it prefers to send `pubsub/pub` as the request body, not as query variable as js http client
