### ISSUE TITLE
Support for /id endpoint

### ISSUE THREAD

**Issue by aphelionz** [ipfs-rust/rust-ipfs#79]
Right now there is static placeholder JSON but this will need to be dynamic

**Comment by koivunej** [comment]
I'll look into this and setting up the node at the same time. At the moment I do not know of a pure-rust RSA keygen, but it then again, for testing purposes at least at the moment, generating an ed25519 key on `init --bits 2048 --profile test` cannot hurt too much.

**Comment by koivunej** [comment]
Got stuck yesterday trying to rig up the rsa keygen without using `openssl` but had to go with that eventually.

**Comment by koivunej** [comment]
https://github.com/ipfs-rust/rust-ipfs/pull/101 with the simplest `/id` without `?arg=another_peerid`.

**Comment by koivunej** [comment]
Current status is that the testing requires #77.

**Comment by koivunej** [comment]
> It's probably best to append the /ipfs/PeerId in the responses [...]

This is now drafted in #110 as more up to date `/p2p/` suffixes. Also created #105 as the #77 came out without support for peer_ids (#104). Currently discussing how to proceed, as I believe the integration test (quoted below) and support for `identify_other` will likely yield a solution to #105 as well as earth some things we need to fix in order to make libp2p_kad work for us.

> Testing plan currently is to setup three `rust-ipfs` nodes (a, b, c), connect (a, b), connect (b, c) then ask a to `identify_other(c)`, this requires kademlia bootstrapping which we do not do, not sure if it's launched automatically on first connection.

Removed mdns part as mdns toggling was already in #104.

**Comment by koivunej** [comment]
A new issue has been split, and the impl in #101, so closing.
